# Zshrc for Samuel Oechsler

# Check system type (Mac/Linux)
if [ "$(uname -s)" = "Linux" ]; then
    linux=true
fi

# Dotfiles directory variable
export DOTDIR=$HOME/dotfiles

# Set the path variable in order for Powerline to work
export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH
if [ $linux ]; then
  export PATH=$HOME/.local/bin:$PATH
fi

# Set the path to the "Oh my zsh" workdir
export ZSH=$HOME/.oh-my-zsh

# Set the Oh my zsh shell theme
ZSH_THEME="agnoster"

# Zsh plugin management
plugins=(
  # Git plugins
  gitfast
  gitignore
  git-flow
  git-auto-fetch

  # Package manager plugins
  yarn
  gradle

  # Compiler plguins
  node
  golang
  docker
  docker-compose

  # System plugins
  osx
  archlinux
  ubuntu
  sudo
  systemd
  colorize
  colored-man-pages
  command-not-found
  gpg-agent

  # Editor plugins
  vscode
  vundle
  xcode
  textastic
  forklift
  iterm2

  # Misc plugins
  emoji
  web-search
  zsh_reload
  zsh-autosuggestions
  wakatime
)

# Oh my zsh import
source $ZSH/oh-my-zsh.sh

# Colorful directory listing
if [ $linux ]; then
    if [ -x /usr/bin/dircolors ]; then
        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
        alias grep="grep --color=auto"
        # LS alias see below
    fi
else
	# On a Mac we have to do it by hand
  export CLICOLOR=1
  export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
fi

# Powerline Shell plugin
function powerline_precmd() {
    PS1="$(powerline-shell --shell zsh $?)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi

# Setting up golang workspace
if [ -z $linux ]; then
	export GOPATH=$HOME/repos/go
fi

# Default editor
export EDITOR="vim"

# Alias commands
alias vi="vim" # VIM
alias cat="ccat" # Pygments
alias screenfetch="neofetch" #Screenfetch
alias dwget="wget -P ~/Downloads/" # Wget to Downloads
alias ls="ls -lh --color" # Advanced ls
if [ -z $linux ]; then
  alias ls="ls -lh"

  # Homebrew cask package manager aliases
  alias cask="brew cask"
fi

# Credential Helper for git
# This is only beacuse sometimes you have
# different credentials in differnet repos, like GitHub
# or Azure DevOps for example. Otherwise this could be saved
# in your global .gitconfig file
alias gitstore="git config credential.helper store"

# DuckDuckGo Bangs
alias wiki='ddg \!w'
alias stack='ddg \!stackoverflow'
alias yt='ddg \!yt'
alias wa='ddg \!wa'

# Compounded cd and ls
cd() {
  builtin cd "$@" && ls
}

# Updater for dotfiles
alias dotupdate='zsh -c "$DOTDIR/scripts/update.sh"'

# Cleanup
unset linux
unset windows

# Startup commands
clear
